### ISSUE TITLE
중간 리팩토링 작업

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#116]
## 📝 Description
- 리팩토링 작업을 수행하고
- 테스트 코드에 대해 되돌아보고, 부족한 부분을 개선한다.

## ☑️ TODO
 

- [ ] 메서드명, 변수명, 필드명 수정
- [ ] 사용하지 않는 메서드 제거
- [ ] 테스트 코드 적합하게 짰는지 확인 및 수정
