### ISSUE TITLE
컴포넌트 생성

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#13]
## 📝 Description
- 일단 리액트 + TypeScript는 여러 강의를 보고 만들 예정으로(배우면서)
- 게시물 리스트를 보여줄 컴포넌트와 Top3 리스트 컴포넌트를 완성하려고 함
- 댓글 리스트 아이템 컴포넌트와 좋아요 리스트 아이템 컴포넌트도 완성
## ☑️ TODO
 - [x] 게시물 리스트 컴포넌트 + mock data로 검증
 - [x] Top3 리스트 컴포넌트 + mock data로 검증
 - [x] 댓글 리스트 아이템 컴포넌트 + mock data로 검증
 - [x] 좋아요 리스트 아이템 컴포넌트 + mock data로 검증
