### ISSUE TITLE
좋아요 누르기 기능 구현

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#59]
## 📝 Description
- 한명의 유저는 하나의 게시글에 좋아요 버튼을 누를 수 있다.
- 유저는 좋아요 버튼을 누르고, 다시 눌렀을 경우 이전에 눌렀던 좋아요 기록이 없어진다.
- 동시에 하나의 게시물에 좋아요 개수를 세는데, 이것도 역시 증가 or 감소해야한다. 

## ☑️ TODO
- [x] Board Entity에서 favoriteCount를 증가 or 감소 시키는 메서드 만들기
- [x] BoardRepository에서 복합키를 넘겨서 Favorite 객체를 가져오는 쿼리 메서드 만들기
- [x] 좋아요 버튼을 두번 눌렀을 때, Favorite 테이블에 기록을 삭제해야 하므로 cascade = ALL을 적용해준다. 
- [x] 좋아요 API 작성(Controller)
- [x] 좋아요 비즈니스 로직 작성(Service)
