### ISSUE TITLE
게시글 관련 테스트 코드 작성

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#67]
## 📝 Description
- 게시글 관련 테스트 코드를 작성한다.

## ☑️ TODO
- [ ] Persistence Layer 테스트 코드 작성 (글 생성, 상세보기)
- [ ] Business Layer 테스트 코드 작성 (글 생성, 상세보기)
- [ ] Presentation Layer 테스트 코드 작성 (글 생성, 상세보기)
- [ ] rest docs 테스트 코드 작성
