### ISSUE TITLE
엔티티 설정

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#7]
## 📝 Description
- 설계해놨던 ERD를 바탕으로 각 엔티티와 레포지토리 서비스를 작성한다.

## ☑️ TODO

- [ ] 사용자 Entity, Repository, Service 작성
- [ ] 게시글 Entity, Repository, Service 작성
- [ ] 좋아요 테이블 Entity, Repository, Service 작성
- [ ] 댓글 Entity, Repository, Service 작성
- [ ] 이미지 Entity, Repository, Service 작성
- [ ] 검색기록 Entity, Repository, Service 작성
