### ISSUE TITLE
회원 관련 테스트 코드 작성

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#75]
## 📝 Description
- 회원 관련 테스트 코드를 미작성하였습니다.

## ☑️ TODO
- [x] 컨트롤러 테스트 코드 작성
- [x] 서비스 테스트 코드 작성
- [x] 레포지토리 테스트 코드 작성
