### ISSUE TITLE
복합키 설정 관련 리팩토링

### ISSUE THREAD

**Issue by beginner0107** [beginner0107/spring-react-blog#89]
## 📝 Description
- JPA 책을 읽던 도중, 복합키에 챕터를 읽던 중 제가 이 프로젝트에서 복합키를 사용했던 점이 생각 났습니다.
- 복합키 설정할 때 꼭 해줘야 하는 작업들이 빠져있었다는 것을 확인하고 이를 적용하기로 하였습니다.

## ☑️ TODO
- [x] Serializable 인터페이스를 구현
- [x] equals, hashCode를 구현
- [x] 테스트 코드로 기능 작동 확인
